[package]
name = "blobfigy"
version = "0.1.0"
edition = "2024"

[lib]
name = "blobfigy"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = "0.28.0"
blobfig = { git = "ssh://git@github.com/jonasrsv42/blobfig", features = ["ndarray"] }
ndarray = "0.17.2"
numpy = "0.28.0"
